apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-ocp-tools
  namespace: testing-pmx3
  labels:
    app.kubernetes.io/name: ms-ocp-tools
    app.kubernetes.io/part-of: ocp-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: diagnosticador-test
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: diagnosticador-test
subjects:
  - kind: ServiceAccount
    name: ms-ocp-tools
    namespace: testing-pmx3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ms-ocp-tools-deployment-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: testing
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: testing
subjects:
  - kind: ServiceAccount
    name: ms-ocp-tools
    namespace: testing-pmx3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ms-ocp-tools-deployment-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: agendador-test
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: agendador-test
subjects:
  - kind: ServiceAccount
    name: ms-ocp-tools
    namespace: testing-pmx3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ms-ocp-tools-deployment-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: pmx-test
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: pmx-test
subjects:
  - kind: ServiceAccount
    name: ms-ocp-tools
    namespace: testing-pmx3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ms-ocp-tools-deployment-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: security-test
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: security-test
subjects:
  - kind: ServiceAccount
    name: ms-ocp-tools
    namespace: testing-pmx3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ms-ocp-tools-deployment-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: testing-pmx1
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: testing-pmx1
subjects:
  - kind: ServiceAccount
    name: ms-ocp-tools
    namespace: testing-pmx3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ms-ocp-tools-deployment-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: testing-pmx2
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: testing-pmx2
subjects:
  - kind: ServiceAccount
    name: ms-ocp-tools
    namespace: testing-pmx3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ms-ocp-tools-deployment-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: testing-pmx3
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: testing-pmx3
subjects:
  - kind: ServiceAccount
    name: ms-ocp-tools
    namespace: testing-pmx3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ms-ocp-tools-deployment-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: testing-pmx4
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: testing-pmx4
subjects:
  - kind: ServiceAccount
    name: ms-ocp-tools
    namespace: testing-pmx3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ms-ocp-tools-deployment-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: testing-diversificacion
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: testing-diversificacion
subjects:
  - kind: ServiceAccount
    name: ms-ocp-tools
    namespace: testing-pmx3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ms-ocp-tools-deployment-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: testing-matrix
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ms-ocp-tools-deployment-reader
  namespace: testing-matrix
subjects:
  - kind: ServiceAccount
    name: ms-ocp-tools
    namespace: testing-pmx3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ms-ocp-tools-deployment-reader
