apiVersion: v1
kind: Secret
metadata:
  name: ms-ocp-tools-postgresql
  namespace: testing-pmx3
  labels:
    app.kubernetes.io/name: ms-ocp-tools-postgresql
    app.kubernetes.io/part-of: ocp-tools
type: Opaque
stringData:
  POSTGRESQL_USER: ocptools
  POSTGRESQL_PASSWORD: REEMPLAZAR_CON_PASSWORD_ALEATORIO
  POSTGRESQL_DATABASE: ocptools

