apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-ocp-tools-postgresql
  namespace: testing-pmx3
  labels:
    app.kubernetes.io/name: ms-ocp-tools-postgresql
    app.kubernetes.io/part-of: ocp-tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

